# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Check CDN

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run!
      run: |
        python cdn_checker.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: top100k
        path: "*_doamins.txt"

    - name: Create release
      continue-on-error: true
      uses: ncipollo/release-action@v1.14.0
      with:
        name: latest
        allowUpdates: true
        tag: latest
        commit: main
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "*_doamins.txt"
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 2
